-- --------------------------------------------------------
-- 主机:                           127.0.0.1
-- 服务器版本:                        5.7.24-log - MySQL Community Server (GPL)
-- 服务器操作系统:                      Win64
-- HeidiSQL 版本:                  10.3.0.5771
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 正在导出表  nacos.config_info 的数据：~4 rows (大约)
/*!40000 ALTER TABLE `config_info` DISABLE KEYS */;
INSERT INTO `config_info` (`id`, `data_id`, `group_id`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `app_name`, `tenant_id`, `c_desc`, `c_use`, `effect`, `type`, `c_schema`) VALUES
	(1, 'system-dev.properties', 'DEFAULT_GROUP', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n\r\nspring.cloud.sentinel.datasource.ds.nacos.server-addr=localhost:8848\r\nspring.cloud.sentinel.datasource.ds.nacos.dataId=${spring.application.name}-sentinel\r\nspring.cloud.sentinel.datasource.ds.nacos.groupId=DEFAULT_GROUP\r\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow', '265922ff3437e1c63fade60b5b2cec8c', '2020-04-10 20:22:05', '2020-04-10 22:50:58', NULL, '127.0.0.1', '', '', 'null', 'null', 'null', 'text', 'null'),
	(3, 'schedule-dev.properties', 'DEFAULT_GROUP', 'server.port = 8085\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\n\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nspring.redis.port = 6379\r\nshiro_redis_session = 600000\r\nmybatis_redis_cache = 600000\r\nshiro_redis_cache = 600000\r\n\r\n\r\ndubbo.scan.basePackages = com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\ndubbo.cloud.subscribed-services=system\r\nspring.main.allow-bean-definition-overriding=true\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n\r\nspring.cloud.sentinel.datasource.ds.nacos.server-addr=localhost:8848\r\nspring.cloud.sentinel.datasource.ds.nacos.dataId=${spring.application.name}-sentinel\r\nspring.cloud.sentinel.datasource.ds.nacos.groupId=DEFAULT_GROUP\r\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow\r\n', 'e14b86ef1a150f8051b448bd43614821', '2020-04-10 20:30:49', '2020-04-10 22:51:18', NULL, '127.0.0.1', '', '', 'null', 'null', 'null', 'text', 'null'),
	(9, 'system-sentinel', 'DEFAULT_GROUP', '[\r\n    {\r\n        "resource": "/system/resources/findResourcesEMUByResources",\r\n        "limitApp": "default",\r\n        "grade": 1,\r\n        "count": 5,\r\n        "strategy": 0,\r\n        "controlBehavior": 0,\r\n        "clusterMode": false\r\n    }\r\n]', '5d74cc83772a8918aff5192e2e23528e', '2020-04-10 22:03:26', '2020-04-10 22:09:56', NULL, '127.0.0.1', '', '', 'null', 'null', 'null', 'json', 'null'),
	(11, 'gateway-dev.properties', 'DEFAULT_GROUP', 'server.port = 1101\r\n\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\nspring.cloud.gateway.discovery.locator.lowerCaseServiceId=true\r\n', 'fadcbc76e53144b9b8ca575b2602e5e8', '2020-04-10 22:25:51', '2020-04-10 22:25:51', NULL, '127.0.0.1', '', '', NULL, NULL, NULL, 'text', NULL);
/*!40000 ALTER TABLE `config_info` ENABLE KEYS */;

-- 正在导出表  nacos.config_info_aggr 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `config_info_aggr` DISABLE KEYS */;
/*!40000 ALTER TABLE `config_info_aggr` ENABLE KEYS */;

-- 正在导出表  nacos.config_info_beta 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `config_info_beta` DISABLE KEYS */;
/*!40000 ALTER TABLE `config_info_beta` ENABLE KEYS */;

-- 正在导出表  nacos.config_info_tag 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `config_info_tag` DISABLE KEYS */;
/*!40000 ALTER TABLE `config_info_tag` ENABLE KEYS */;

-- 正在导出表  nacos.config_tags_relation 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `config_tags_relation` DISABLE KEYS */;
/*!40000 ALTER TABLE `config_tags_relation` ENABLE KEYS */;

-- 正在导出表  nacos.group_capacity 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `group_capacity` DISABLE KEYS */;
/*!40000 ALTER TABLE `group_capacity` ENABLE KEYS */;

-- 正在导出表  nacos.his_config_info 的数据：~15 rows (大约)
/*!40000 ALTER TABLE `his_config_info` DISABLE KEYS */;
INSERT INTO `his_config_info` (`id`, `nid`, `data_id`, `group_id`, `app_name`, `content`, `md5`, `gmt_create`, `gmt_modified`, `src_user`, `src_ip`, `op_type`, `tenant_id`) VALUES
	(0, 1, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost', '56f735f325545747760aa460612f78de', '2020-04-10 20:22:05', '2020-04-10 20:22:05', NULL, '127.0.0.1', 'I', ''),
	(1, 2, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost', '56f735f325545747760aa460612f78de', '2020-04-10 20:23:00', '2020-04-10 20:23:00', NULL, '127.0.0.1', 'U', ''),
	(0, 3, 'schedule-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8085\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\n\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nspring.redis.port = 6379\r\nshiro_redis_session = 600000\r\nmybatis_redis_cache = 600000\r\nshiro_redis_cache = 600000\r\n\r\n\r\ndubbo.scan.basePackages = com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\ndubbo.cloud.subscribed-services=system\r\nspring.main.allow-bean-definition-overriding=true\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', 'b265a607481355f91eca738b3a64e989', '2020-04-10 20:30:48', '2020-04-10 20:30:49', NULL, '127.0.0.1', 'I', ''),
	(0, 4, 'zuul-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 1101\r\nzuul.sensitiveHeaders = "*"\r\nzuul.routes.a.path = /system/**\r\nzuul.routes.a.url = http://localhost:8083\r\nzuul.routes.b.path = /schedule/**\r\nzuul.routes.b.url = http://localhost:8085', 'ee55fe7e1e012d59fed05fdad3f09655', '2020-04-10 20:32:45', '2020-04-10 20:32:45', NULL, '127.0.0.1', 'I', ''),
	(1, 5, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n', 'f8eac0501c3105cf0fad478309141dec', '2020-04-10 20:33:09', '2020-04-10 20:33:09', NULL, '127.0.0.1', 'U', ''),
	(1, 6, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n', 'f8eac0501c3105cf0fad478309141dec', '2020-04-10 20:53:44', '2020-04-10 20:53:44', NULL, '127.0.0.1', 'U', ''),
	(3, 7, 'schedule-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8085\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\n\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nspring.redis.port = 6379\r\nshiro_redis_session = 600000\r\nmybatis_redis_cache = 600000\r\nshiro_redis_cache = 600000\r\n\r\n\r\ndubbo.scan.basePackages = com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\ndubbo.cloud.subscribed-services=system\r\nspring.main.allow-bean-definition-overriding=true\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848', 'b265a607481355f91eca738b3a64e989', '2020-04-10 20:53:59', '2020-04-10 20:53:59', NULL, '127.0.0.1', 'U', ''),
	(3, 8, 'schedule-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8085\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\n\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nspring.redis.port = 6379\r\nshiro_redis_session = 600000\r\nmybatis_redis_cache = 600000\r\nshiro_redis_cache = 600000\r\n\r\n\r\ndubbo.scan.basePackages = com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\ndubbo.cloud.subscribed-services=system\r\nspring.main.allow-bean-definition-overriding=true\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n', '896fbede27d9da98f18dc2fb3aeaaa32', '2020-04-10 22:00:05', '2020-04-10 22:00:06', NULL, '127.0.0.1', 'U', ''),
	(0, 9, 'system-sentinel', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        "resource": "/hello",\r\n        "limitApp": "default",\r\n        "grade": 1,\r\n        "count": 5,\r\n        "strategy": 0,\r\n        "controlBehavior": 0,\r\n        "clusterMode": false\r\n    }\r\n]', '9e52cab07d87efcf3817c4ed926fca94', '2020-04-10 22:03:26', '2020-04-10 22:03:26', NULL, '127.0.0.1', 'I', ''),
	(9, 10, 'system-sentinel', 'DEFAULT_GROUP', '', '[\r\n    {\r\n        "resource": "/hello",\r\n        "limitApp": "default",\r\n        "grade": 1,\r\n        "count": 5,\r\n        "strategy": 0,\r\n        "controlBehavior": 0,\r\n        "clusterMode": false\r\n    }\r\n]', '9e52cab07d87efcf3817c4ed926fca94', '2020-04-10 22:09:55', '2020-04-10 22:09:56', NULL, '127.0.0.1', 'U', ''),
	(0, 11, 'gateway-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 1101\r\n\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\n\r\nspring.cloud.gateway.discovery.locator.enabled=true\r\nspring.cloud.gateway.discovery.locator.lowerCaseServiceId=true\r\n', 'fadcbc76e53144b9b8ca575b2602e5e8', '2020-04-10 22:25:51', '2020-04-10 22:25:51', NULL, '127.0.0.1', 'I', ''),
	(1, 12, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n', '4f32bd754184e8c7e1e1d305543b072e', '2020-04-10 22:27:48', '2020-04-10 22:27:48', NULL, '127.0.0.1', 'U', ''),
	(4, 13, 'zuul-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 1101\r\nzuul.sensitiveHeaders = "*"\r\nzuul.routes.a.path = /system/**\r\nzuul.routes.a.url = http://localhost:8083\r\nzuul.routes.b.path = /schedule/**\r\nzuul.routes.b.url = http://localhost:8085', 'ee55fe7e1e012d59fed05fdad3f09655', '2020-04-10 22:43:18', '2020-04-10 22:43:18', NULL, '127.0.0.1', 'D', ''),
	(1, 14, 'system-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8083\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nspring.redis.port = 6379\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\nshiro_redis_cache = 600000\r\nshiro_redis_session = 600000\r\n\r\n\r\ndubbo.provider.filter = providerFilter\r\n\r\ndubbo.scan.base-packages=com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n\r\nspring.cloud.sentinel.datasource.ds.nacos.dataId=${spring.application.name}-sentinel\r\nspring.cloud.sentinel.datasource.ds.nacos.groupId=DEFAULT_GROUP\r\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow', 'a2eee80b692b71b4de78165338479db2', '2020-04-10 22:50:58', '2020-04-10 22:50:58', NULL, '127.0.0.1', 'U', ''),
	(3, 15, 'schedule-dev.properties', 'DEFAULT_GROUP', '', 'server.port = 8085\r\nspring.datasource.password = root\r\nspring.datasource.username = root\r\nspring.datasource.driver-class-name = com.mysql.jdbc.Driver\r\nspring.datasource.url = jdbc:mysql://localhost:3306/dubbo-app?useUnicode=true&characterEncoding=utf-8\r\nspring.datasource.druid.initial-Size = 5\r\nspring.datasource.druid.min-Idle = 5\r\nspring.datasource.druid.max-Active = 20\r\nspring.datasource.druid.max-Wait = 60000\r\nspring.datasource.druid.time-Between-Eviction-Runs-Millis = 60000\r\nspring.datasource.druid.min-Evictable-Idle-Time-Millis = 300000\r\nspring.datasource.druid.validation-Query = SELECT 1 FROM DUAL\r\nspring.datasource.druid.test-While-Idle = true\r\nspring.datasource.druid.test-On-Borrow = false\r\nspring.datasource.druid.test-On-Return = false\r\nspring.datasource.druid.filters = stat,wall,logback\r\nconfigLocation = classpath:mybatis-config.xml\r\nmybatis.mapper-locations = classpath:mapping/*/*.xml\r\n\r\nspring.redis.host = 127.0.0.1\r\nspring.redis.password =\r\nspring.redis.port = 6379\r\nshiro_redis_session = 600000\r\nmybatis_redis_cache = 600000\r\nshiro_redis_cache = 600000\r\n\r\n\r\ndubbo.scan.basePackages = com.wangsong\r\ndubbo.protocol.name=dubbo\r\ndubbo.protocol.port=-1\r\ndubbo.registry.address=spring-cloud://localhost\r\ndubbo.cloud.subscribed-services=system\r\nspring.main.allow-bean-definition-overriding=true\r\nspring.cloud.nacos.discovery.server-addr=127.0.0.1:8848\r\nspring.cloud.sentinel.transport.dashboard=localhost:8080\r\n\r\nspring.cloud.sentinel.datasource.ds.nacos.dataId=${spring.application.name}-sentinel\r\nspring.cloud.sentinel.datasource.ds.nacos.groupId=DEFAULT_GROUP\r\nspring.cloud.sentinel.datasource.ds.nacos.rule-type=flow\r\n', 'ed9002c7591386046a53a3554046310c', '2020-04-10 22:51:18', '2020-04-10 22:51:18', NULL, '127.0.0.1', 'U', '');
/*!40000 ALTER TABLE `his_config_info` ENABLE KEYS */;

-- 正在导出表  nacos.permissions 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `permissions` DISABLE KEYS */;
/*!40000 ALTER TABLE `permissions` ENABLE KEYS */;

-- 正在导出表  nacos.roles 的数据：~1 rows (大约)
/*!40000 ALTER TABLE `roles` DISABLE KEYS */;
INSERT INTO `roles` (`username`, `role`) VALUES
	('nacos', 'ROLE_ADMIN');
/*!40000 ALTER TABLE `roles` ENABLE KEYS */;

-- 正在导出表  nacos.tenant_capacity 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `tenant_capacity` DISABLE KEYS */;
/*!40000 ALTER TABLE `tenant_capacity` ENABLE KEYS */;

-- 正在导出表  nacos.tenant_info 的数据：~0 rows (大约)
/*!40000 ALTER TABLE `tenant_info` DISABLE KEYS */;
/*!40000 ALTER TABLE `tenant_info` ENABLE KEYS */;

-- 正在导出表  nacos.users 的数据：~1 rows (大约)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`username`, `password`, `enabled`) VALUES
	('nacos', '$2a$10$EuWPZHzz32dJN7jexM34MOeYirDdFAZm2kuWj7VEOJhhZkDrxfvUu', 1);
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
